services:
  - type: web
    name: elite-forex-pro
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: bash start.sh
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: mysql
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: elite-forex-pro-db
    databaseName: crypto_broker
    user: eliteforexpro
    plan: starter
    region: oregon
